# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import telemetry_pb2 as telemetry__pb2


class TelemetryServiceStub(object):
    """The gRPC Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/telemetry.TelemetryService/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryPoint.SerializeToString,
                response_deserializer=telemetry__pb2.TelemetryResponse.FromString,
                )


class TelemetryServiceServicer(object):
    """The gRPC Service definition
    """

    def StreamTelemetry(self, request_iterator, context):
        """Client streams continuous telemetry data. 
        Server responds once when the client closes the stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryPoint.FromString,
                    response_serializer=telemetry__pb2.TelemetryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'telemetry.TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TelemetryService(object):
    """The gRPC Service definition
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/telemetry.TelemetryService/StreamTelemetry',
            telemetry__pb2.TelemetryPoint.SerializeToString,
            telemetry__pb2.TelemetryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
